from grpc.aio import ClientCallDetails, StreamStreamClientInterceptor, StreamUnaryClientInterceptor, UnaryStreamClientInterceptor, UnaryUnaryClientInterceptor
from grpc.aio._call import StreamStreamCall as StreamStreamCall, StreamUnaryCall as StreamUnaryCall, UnaryStreamCall as UnaryStreamCall, UnaryUnaryCall as UnaryUnaryCall
from grpc.aio._typing import RequestIterableType as RequestIterableType, RequestType as RequestType, ResponseIterableType as ResponseIterableType, ResponseType as ResponseType
from typing import Callable

class _GenericAsyncClientInterceptor(UnaryUnaryClientInterceptor, UnaryStreamClientInterceptor, StreamUnaryClientInterceptor, StreamStreamClientInterceptor):
    def __init__(self, interceptor_function: Callable) -> None: ...
    async def intercept_unary_unary(self, continuation: Callable[[ClientCallDetails, RequestType], UnaryUnaryCall], client_call_details: ClientCallDetails, request: RequestType) -> UnaryUnaryCall | ResponseType: ...
    async def intercept_unary_stream(self, continuation: Callable[[ClientCallDetails, RequestType], UnaryStreamCall], client_call_details: ClientCallDetails, request: RequestType) -> ResponseIterableType | UnaryStreamCall: ...
    async def intercept_stream_unary(self, continuation: Callable[[ClientCallDetails, RequestType], StreamUnaryCall], client_call_details: ClientCallDetails, request_iterator: RequestIterableType) -> StreamUnaryCall: ...
    async def intercept_stream_stream(self, continuation: Callable[[ClientCallDetails, RequestType], StreamStreamCall], client_call_details: ClientCallDetails, request_iterator: RequestIterableType) -> ResponseIterableType | StreamStreamCall: ...

def async_header_adder_interceptor(headers: list[str], values: list[str] | list[bytes]): ...
