import abc
from .abstract import MutationResult as MutationResult
from .search_result import SearchResult as SearchResult
from .types import Status as Status
from .utils import check_status as check_status
from pymilvus.exceptions import MilvusException as MilvusException
from pymilvus.grpc_gen import milvus_pb2 as milvus_pb2
from typing import Any, Callable

class AbstractFuture(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def result(self, **kwargs): ...
    @abc.abstractmethod
    def cancel(self): ...
    @abc.abstractmethod
    def done(self): ...

class Future(AbstractFuture, metaclass=abc.ABCMeta):
    def __init__(self, future: Any, done_callback: Callable | None = None, pre_exception: Callable | None = None, **kwargs) -> None: ...
    def add_callback(self, func: Callable): ...
    def __del__(self) -> None: ...
    @abc.abstractmethod
    def on_response(self, response: Callable): ...
    def result(self, **kwargs): ...
    def cancel(self) -> None: ...
    def is_done(self): ...
    def done(self) -> None: ...
    def exception(self) -> None: ...

class SearchFuture(Future):
    def on_response(self, response: milvus_pb2.SearchResults): ...

class MutationFuture(Future):
    def on_response(self, response: Any): ...

class CreateIndexFuture(Future):
    def on_response(self, response: Any): ...

class CreateFlatIndexFuture(AbstractFuture):
    def __init__(self, res: Any, done_callback: Callable | None = None, pre_exception: Callable | None = None) -> None: ...
    def add_callback(self, func: Callable): ...
    def __del__(self) -> None: ...
    def on_response(self, response: Any): ...
    def result(self): ...
    def cancel(self) -> None: ...
    def is_done(self): ...
    def done(self) -> None: ...
    def exception(self) -> None: ...

class FlushFuture(Future):
    def on_response(self, response: Any): ...

class LoadCollectionFuture(Future):
    def on_response(self, response: Any): ...

class LoadPartitionsFuture(Future):
    def on_response(self, response: Any): ...
