import grpc
from . import entity_helper as entity_helper, ts_utils as ts_utils, utils as utils
from .abstract import AnnSearchRequest as AnnSearchRequest, BaseRanker as BaseRanker, CollectionSchema as CollectionSchema, FieldSchema as FieldSchema, MutationResult as MutationResult
from .async_interceptor import async_header_adder_interceptor as async_header_adder_interceptor
from .check import check_pass_param as check_pass_param, is_legal_host as is_legal_host, is_legal_port as is_legal_port
from .constants import ITERATOR_SESSION_TS_FIELD as ITERATOR_SESSION_TS_FIELD
from .prepare import Prepare as Prepare
from .search_result import SearchResult as SearchResult
from .types import AnalyzeResult as AnalyzeResult, CompactionState as CompactionState, DataType as DataType, DatabaseInfo as DatabaseInfo, HybridExtraList as HybridExtraList, IndexState as IndexState, LoadState as LoadState, ReplicaInfo as ReplicaInfo, Shard as Shard, State as State, Status as Status, get_cost_extra as get_cost_extra
from .utils import check_invalid_binary_vector as check_invalid_binary_vector, check_status as check_status, get_server_type as get_server_type, is_successful as is_successful, len_of as len_of
from _typeshed import Incomplete
from pymilvus.client.types import GrantInfo as GrantInfo, ResourceGroupConfig as ResourceGroupConfig
from pymilvus.decorators import ignore_unimplemented as ignore_unimplemented, retry_on_rpc_failure as retry_on_rpc_failure
from pymilvus.exceptions import AmbiguousIndexName as AmbiguousIndexName, DescribeCollectionException as DescribeCollectionException, ErrorCode as ErrorCode, ExceptionsMessage as ExceptionsMessage, MilvusException as MilvusException, ParamError as ParamError
from pymilvus.grpc_gen import common_pb2 as common_pb2, milvus_pb2_grpc as milvus_pb2_grpc
from pymilvus.orm.schema import Function as Function
from pymilvus.settings import Config as Config

class AsyncGrpcHandler:
    callbacks: Incomplete
    def __init__(self, uri: str = ..., host: str = '', port: str = '', channel: grpc.aio.Channel | None = None, **kwargs) -> None: ...
    def __enter__(self): ...
    def __exit__(self, exc_type: object, exc_val: object, exc_tb: object): ...
    async def close(self) -> None: ...
    @property
    def server_address(self): ...
    def get_server_type(self): ...
    async def ensure_channel_ready(self) -> None: ...
    async def create_collection(self, collection_name: str, fields: list, timeout: float | None = None, **kwargs): ...
    async def drop_collection(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    async def load_collection(self, collection_name: str, replica_number: int | None = None, timeout: float | None = None, **kwargs): ...
    async def wait_for_loading_collection(self, collection_name: str, timeout: float | None = None, is_refresh: bool = False, **kwargs): ...
    async def get_loading_progress(self, collection_name: str, partition_names: list[str] | None = None, timeout: float | None = None, is_refresh: bool = False, **kwargs): ...
    async def describe_collection(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    async def has_collection(self, collection_name: str, timeout: float | None = None, **kwargs) -> bool: ...
    async def list_collections(self, timeout: float | None = None, **kwargs) -> list[str]: ...
    async def get_collection_stats(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    async def get_partition_stats(self, collection_name: str, partition_name: str, timeout: float | None = None, **kwargs): ...
    async def get_load_state(self, collection_name: str, partition_names: list[str] | None = None, timeout: float | None = None, **kwargs): ...
    async def refresh_load(self, collection_name: str, partition_names: list[str] | None = None, timeout: float | None = None, **kwargs): ...
    async def get_server_version(self, timeout: float | None = None, **kwargs) -> str: ...
    async def describe_replica(self, collection_name: str, timeout: float | None = None, **kwargs) -> list[ReplicaInfo]: ...
    async def rename_collection(self, old_name: str, new_name: str, new_db_name: str = '', timeout: float | None = None, **kwargs): ...
    async def release_collection(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    async def insert_rows(self, collection_name: str, entities: dict | list[dict], partition_name: str | None = None, schema: dict | None = None, timeout: float | None = None, **kwargs): ...
    async def delete(self, collection_name: str, expression: str, partition_name: str | None = None, timeout: float | None = None, **kwargs): ...
    async def upsert(self, collection_name: str, entities: list, partition_name: str | None = None, timeout: float | None = None, **kwargs): ...
    async def upsert_rows(self, collection_name: str, entities: list, partition_name: str | None = None, timeout: float | None = None, **kwargs): ...
    async def search(self, collection_name: str, data: list[list[float]] | utils.SparseMatrixInputType, anns_field: str, param: dict, limit: int, expression: str | None = None, partition_names: list[str] | None = None, output_fields: list[str] | None = None, round_decimal: int = -1, timeout: float | None = None, ranker: Function | None = None, **kwargs): ...
    async def hybrid_search(self, collection_name: str, reqs: list[AnnSearchRequest], rerank: BaseRanker | Function, limit: int, partition_names: list[str] | None = None, output_fields: list[str] | None = None, round_decimal: int = -1, timeout: float | None = None, **kwargs): ...
    async def create_index(self, collection_name: str, field_name: str, params: dict, timeout: float | None = None, **kwargs): ...
    async def wait_for_creating_index(self, collection_name: str, index_name: str, timeout: float | None = None, **kwargs): ...
    async def get_index_state(self, collection_name: str, index_name: str, timeout: float | None = None, timestamp: int | None = None, **kwargs): ...
    async def drop_index(self, collection_name: str, field_name: str, index_name: str, timeout: float | None = None, **kwargs): ...
    async def create_partition(self, collection_name: str, partition_name: str, timeout: float | None = None, **kwargs): ...
    async def drop_partition(self, collection_name: str, partition_name: str, timeout: float | None = None, **kwargs): ...
    async def load_partitions(self, collection_name: str, partition_names: list[str], replica_number: int | None = None, timeout: float | None = None, **kwargs): ...
    async def wait_for_loading_partitions(self, collection_name: str, partition_names: list[str], timeout: float | None = None, is_refresh: bool = False, **kwargs): ...
    async def release_partitions(self, collection_name: str, partition_names: list[str], timeout: float | None = None, **kwargs): ...
    async def has_partition(self, collection_name: str, partition_name: str, timeout: float | None = None, **kwargs) -> bool: ...
    async def list_partitions(self, collection_name: str, timeout: float | None = None, **kwargs) -> list[str]: ...
    async def get(self, collection_name: str, ids: list[int], output_fields: list[str] | None = None, partition_names: list[str] | None = None, timeout: float | None = None, **kwargs): ...
    async def query(self, collection_name: str, expr: str, output_fields: list[str] | None = None, partition_names: list[str] | None = None, timeout: float | None = None, strict_float32: bool = False, **kwargs): ...
    async def alloc_timestamp(self, timeout: float | None = None, **kwargs) -> int: ...
    async def alter_collection_properties(self, collection_name: str, properties: dict, timeout: float | None = None, **kwargs): ...
    async def drop_collection_properties(self, collection_name: str, property_keys: list[str], timeout: float | None = None, **kwargs): ...
    async def alter_collection_field(self, collection_name: str, field_name: str, field_params: dict, timeout: float | None = None, **kwargs): ...
    async def add_collection_field(self, collection_name: str, field_schema: FieldSchema, timeout: float | None = None, **kwargs): ...
    async def list_indexes(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    async def describe_index(self, collection_name: str, index_name: str, timeout: float | None = None, timestamp: int | None = None, **kwargs): ...
    async def alter_index_properties(self, collection_name: str, index_name: str, properties: dict, timeout: float | None = None, **kwargs): ...
    async def drop_index_properties(self, collection_name: str, index_name: str, property_keys: list[str], timeout: float | None = None, **kwargs): ...
    async def create_alias(self, collection_name: str, alias: str, timeout: float | None = None, **kwargs): ...
    async def drop_alias(self, alias: str, timeout: float | None = None, **kwargs): ...
    async def alter_alias(self, collection_name: str, alias: str, timeout: float | None = None, **kwargs): ...
    async def describe_alias(self, alias: str, timeout: float | None = None, **kwargs): ...
    async def list_aliases(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    def reset_db_name(self, db_name: str): ...
    async def create_database(self, db_name: str, properties: dict | None = None, timeout: float | None = None, **kwargs): ...
    async def drop_database(self, db_name: str, timeout: float | None = None, **kwargs): ...
    async def list_database(self, timeout: float | None = None, **kwargs): ...
    async def alter_database(self, db_name: str, properties: dict, timeout: float | None = None, **kwargs): ...
    async def drop_database_properties(self, db_name: str, property_keys: list[str], timeout: float | None = None, **kwargs): ...
    async def describe_database(self, db_name: str, timeout: float | None = None, **kwargs): ...
    async def create_privilege_group(self, privilege_group: str, timeout: float | None = None, **kwargs): ...
    async def drop_privilege_group(self, privilege_group: str, timeout: float | None = None, **kwargs): ...
    async def list_privilege_groups(self, timeout: float | None = None, **kwargs): ...
    async def add_privileges_to_group(self, privilege_group: str, privileges: list[str], timeout: float | None = None, **kwargs): ...
    async def remove_privileges_from_group(self, privilege_group: str, privileges: list[str], timeout: float | None = None, **kwargs): ...
    async def create_user(self, user: str, password: str, timeout: float | None = None, **kwargs): ...
    async def drop_user(self, user: str, timeout: float | None = None, **kwargs): ...
    async def update_password(self, user: str, old_password: str, new_password: str, timeout: float | None = None, **kwargs): ...
    async def list_users(self, timeout: float | None = None, **kwargs): ...
    async def describe_user(self, username: str, include_role_info: bool, timeout: float | None = None, **kwargs): ...
    async def create_role(self, role_name: str, timeout: float | None = None, **kwargs): ...
    async def drop_role(self, role_name: str, force_drop: bool = False, timeout: float | None = None, **kwargs): ...
    async def grant_role(self, username: str, role_name: str, timeout: float | None = None, **kwargs): ...
    async def revoke_role(self, username: str, role_name: str, timeout: float | None = None, **kwargs): ...
    async def describe_role(self, role_name: str, include_user_info: bool, timeout: float | None = None, **kwargs): ...
    async def list_roles(self, include_user_info: bool, timeout: float | None = None, **kwargs): ...
    async def select_grant_for_one_role(self, role_name: str, db_name: str, timeout: float | None = None, **kwargs): ...
    async def grant_privilege(self, role_name: str, object: str, object_name: str, privilege: str, db_name: str, timeout: float | None = None, **kwargs): ...
    async def revoke_privilege(self, role_name: str, object: str, object_name: str, privilege: str, db_name: str, timeout: float | None = None, **kwargs): ...
    async def grant_privilege_v2(self, role_name: str, privilege: str, collection_name: str, db_name: str | None = None, timeout: float | None = None, **kwargs): ...
    async def revoke_privilege_v2(self, role_name: str, privilege: str, collection_name: str, db_name: str | None = None, timeout: float | None = None, **kwargs): ...
    async def create_resource_group(self, name: str, timeout: float | None = None, **kwargs): ...
    async def drop_resource_group(self, name: str, timeout: float | None = None, **kwargs): ...
    async def update_resource_groups(self, configs: dict[str, ResourceGroupConfig], timeout: float | None = None, **kwargs): ...
    async def describe_resource_group(self, name: str, timeout: float | None = None, **kwargs): ...
    async def list_resource_groups(self, timeout: float | None = None, **kwargs): ...
    async def transfer_replica(self, source: str, target: str, collection_name: str, num_replica: int, timeout: float | None = None, **kwargs): ...
    async def flush(self, collection_names: list[str], timeout: float | None = None, **kwargs): ...
    async def compact(self, collection_name: str, is_clustering: bool | None = False, timeout: float | None = None, **kwargs) -> int: ...
    async def get_compaction_state(self, compaction_id: int, timeout: float | None = None, **kwargs): ...
    async def run_analyzer(self, texts: str | list[str], analyzer_params: str | dict | None = None, with_hash: bool = False, with_detail: bool = False, collection_name: str | None = None, field_name: str | None = None, analyzer_names: str | list[str] | None = None, timeout: float | None = None, **kwargs): ...
