from _typeshed import Incomplete
from pymilvus.grpc_gen import common_pb2 as common_pb2

ConsistencyLevel: Incomplete
LOGICAL_BITS: int
LOGICAL_BITS_MASK: Incomplete
EVENTUALLY_TS: int
BOUNDED_TS: int
DEFAULT_CONSISTENCY_LEVEL: Incomplete
DEFAULT_RESOURCE_GROUP: str
DYNAMIC_FIELD_NAME: str
REDUCE_STOP_FOR_BEST: str
COLLECTION_ID: str
GROUP_BY_FIELD: str
GROUP_SIZE: str
RANK_GROUP_SCORER: str
STRICT_GROUP_SIZE: str
JSON_PATH: str
JSON_CAST_TYPE: str
ITERATOR_FIELD: str
ITERATOR_SESSION_TS_FIELD: str
ITER_SEARCH_V2_KEY: str
ITER_SEARCH_BATCH_SIZE_KEY: str
ITER_SEARCH_LAST_BOUND_KEY: str
ITER_SEARCH_ID_KEY: str
PAGE_RETAIN_ORDER_FIELD: str
HINTS: str
RANKER_TYPE_RRF: str
RANKER_TYPE_WEIGHTED: str
GUARANTEE_TIMESTAMP: str
