from .types import DataType as DataType
from .utils import SciPyHelper as SciPyHelper, SparseMatrixInputType as SparseMatrixInputType, SparseRowOutputType as SparseRowOutputType, sparse_parse_single_row as sparse_parse_single_row
from _typeshed import Incomplete
from pymilvus.exceptions import DataNotMatchException as DataNotMatchException, ExceptionsMessage as ExceptionsMessage, MilvusException as MilvusException, ParamError as ParamError
from pymilvus.grpc_gen import schema_pb2 as schema_types
from pymilvus.settings import Config as Config
from typing import Any, Iterable

logger: Incomplete
CHECK_STR_ARRAY: bool

def entity_is_sparse_matrix(entity: Any): ...
def sparse_rows_to_proto(data: SparseMatrixInputType) -> schema_types.SparseFloatArray: ...
def sparse_proto_to_rows(sfv: schema_types.SparseFloatArray, start: int | None = None, end: int | None = None) -> Iterable[SparseRowOutputType]: ...
def get_input_num_rows(entity: Any) -> int: ...
def entity_type_to_dtype(entity_type: Any): ...
def get_max_len_of_var_char(field_info: dict) -> int: ...
def convert_to_str_array(orig_str_arr: Any, field_info: dict, check: bool = True): ...
def entity_to_str_arr(entity_values: Any, field_info: Any, check: bool = True): ...
def convert_to_json(obj: object): ...
def convert_to_json_arr(objs: list[object], field_info: Any): ...
def entity_to_json_arr(entity_values: dict, field_info: Any): ...
def convert_to_array_arr(objs: list[Any], field_info: Any): ...
def convert_to_array(obj: list[Any], field_info: Any): ...
def entity_to_array_arr(entity_values: list[Any], field_info: Any): ...
def pack_field_value_to_field_data(field_value: Any, field_data: schema_types.FieldData, field_info: Any): ...
def entity_to_field_data(entity: dict, field_info: Any, num_rows: int) -> schema_types.FieldData: ...
def extract_dynamic_field_from_result(raw: Any): ...
def extract_array_row_data_with_validity(field_data: Any, entity_rows: list[dict], row_count: int): ...
def extract_array_row_data_no_validity(field_data: Any, entity_rows: list[dict], row_count: int): ...
def extract_array_row_data(field_data: Any, index: int): ...
def extract_row_data_from_fields_data_v2(field_data: Any, entity_rows: list[dict]) -> bool: ...
def extract_row_data_from_fields_data(fields_data: Any, index: Any, dynamic_output_fields: list | None = None): ...
