import grpc
from typing import Any, Callable, NamedTuple

def current_time_ms() -> str: ...

class _GenericClientInterceptor(grpc.UnaryUnaryClientInterceptor, grpc.UnaryStreamClientInterceptor, grpc.StreamUnaryClientInterceptor, grpc.StreamStreamClientInterceptor):
    def __init__(self, interceptor_function: Callable) -> None: ...
    def intercept_unary_unary(self, continuation: Callable, client_call_details: Any, request: Any): ...
    def intercept_unary_stream(self, continuation: Callable, client_call_details: Any, request: Any): ...
    def intercept_stream_unary(self, continuation: Callable, client_call_details: Any, request_iterator: Any): ...
    def intercept_stream_stream(self, continuation: Callable, client_call_details: Any, request_iterator: Any): ...

class ClientCallDetailsTuple(NamedTuple):
    method: Any
    timeout: Any
    metadata: Any
    credentials: Any

class _ClientCallDetails(ClientCallDetailsTuple, grpc.ClientCallDetails): ...

def header_adder_interceptor(headers: list, values: list): ...
