import datetime
from .constants import BOUNDED_TS as BOUNDED_TS, EVENTUALLY_TS as EVENTUALLY_TS, GUARANTEE_TIMESTAMP as GUARANTEE_TIMESTAMP, ITERATOR_FIELD as ITERATOR_FIELD
from .singleton_utils import Singleton as Singleton
from .types import get_consistency_level as get_consistency_level
from .utils import hybridts_to_unixtime as hybridts_to_unixtime
from _typeshed import Incomplete
from pymilvus.grpc_gen import common_pb2 as common_pb2

ConsistencyLevel: Incomplete

class GTsDict(metaclass=Singleton):
    def __init__(self) -> None: ...
    def update(self, collection: int, ts: int): ...
    def get(self, collection: int): ...

def update_collection_ts(collection: int, ts: int): ...
def update_ts_on_mutation(collection: int): ...
def get_collection_ts(collection: int): ...
def get_collection_timestamp(collection: int): ...
def get_collection_datetime(collection: int, tz: datetime.timezone | None = None): ...
def get_eventually_ts(): ...
def get_bounded_ts(): ...
def construct_guarantee_ts(collection_name: str, kwargs: dict): ...
