from . import utils as utils
from _typeshed import Incomplete
from enum import IntEnum
from pymilvus.exceptions import AutoIDException as AutoIDException, ExceptionsMessage as ExceptionsMessage, InvalidConsistencyLevel as InvalidConsistencyLevel
from pymilvus.grpc_gen import common_pb2 as common_pb2, milvus_pb2 as milvus_types, rg_pb2 as rg_pb2, schema_pb2 as schema_pb2
from typing import Any, ClassVar, TypeVar

Status = TypeVar('Status')
ConsistencyLevel: Incomplete
logger: Incomplete

class OmitZeroDict(dict):
    def omit_zero_len(self): ...

class Status:
    SUCCESS: int
    UNEXPECTED_ERROR: int
    CONNECT_FAILED: int
    PERMISSION_DENIED: int
    COLLECTION_NOT_EXISTS: int
    ILLEGAL_ARGUMENT: int
    ILLEGAL_RANGE: int
    ILLEGAL_DIMENSION: int
    ILLEGAL_INDEX_TYPE: int
    ILLEGAL_COLLECTION_NAME: int
    ILLEGAL_TOPK: int
    ILLEGAL_ROWRECORD: int
    ILLEGAL_VECTOR_ID: int
    ILLEGAL_SEARCH_RESULT: int
    FILE_NOT_FOUND: int
    META_FAILED: int
    CACHE_FAILED: int
    CANNOT_CREATE_FOLDER: int
    CANNOT_CREATE_FILE: int
    CANNOT_DELETE_FOLDER: int
    CANNOT_DELETE_FILE: int
    BUILD_INDEX_ERROR: int
    ILLEGAL_NLIST: int
    ILLEGAL_METRIC_TYPE: int
    OUT_OF_MEMORY: int
    INDEX_NOT_EXIST: int
    EMPTY_COLLECTION: int
    code: Incomplete
    message: Incomplete
    def __init__(self, code: int = ..., message: str = 'Success') -> None: ...
    def __eq__(self, other: int | Status): ...
    def OK(self): ...

class DataType(IntEnum):
    NONE = 0
    BOOL = ...
    INT8 = ...
    INT16 = ...
    INT32 = ...
    INT64 = ...
    FLOAT = ...
    DOUBLE = ...
    STRING = ...
    VARCHAR = ...
    ARRAY = ...
    JSON = ...
    GEOMETRY = ...
    BINARY_VECTOR = ...
    FLOAT_VECTOR = ...
    FLOAT16_VECTOR = ...
    BFLOAT16_VECTOR = ...
    SPARSE_FLOAT_VECTOR = ...
    INT8_VECTOR = ...
    UNKNOWN = 999

class FunctionType(IntEnum):
    UNKNOWN = 0
    BM25 = 1
    TEXTEMBEDDING = 2
    RERANK = 3

class RangeType(IntEnum):
    LT = 0
    LTE = 1
    EQ = 2
    GT = 3
    GTE = 4
    NE = 5

class IndexType(IntEnum):
    INVALID = 0
    FLAT = 1
    IVFLAT = 2
    IVF_SQ8 = 3
    RNSG = 4
    IVF_SQ8H = 5
    IVF_PQ = 6
    HNSW = 11
    ANNOY = 12
    IVF_FLAT = IVFLAT
    IVF_SQ8_H = IVF_SQ8H

class MetricType(IntEnum):
    INVALID = 0
    L2 = 1
    IP = 2
    HAMMING = 3
    JACCARD = 4
    TANIMOTO = 5
    SUBSTRUCTURE = 6
    SUPERSTRUCTURE = 7

class IndexState(IntEnum):
    IndexStateNone = 0
    Unissued = 1
    InProgress = 2
    Finished = 3
    Failed = 4
    Deleted = 5

class PlaceholderType(IntEnum):
    NoneType = 0
    BinaryVector = 100
    FloatVector = 101
    FLOAT16_VECTOR = 102
    BFLOAT16_VECTOR = 103
    SparseFloatVector = 104
    Int8Vector = 105
    VARCHAR = 21

class State(IntEnum):
    UndefiedState = 0
    Executing = 1
    Completed = 2
    @staticmethod
    def new(s: int): ...

class LoadState(IntEnum):
    NotExist = 0
    NotLoad = 1
    Loading = 2
    Loaded = 3

class CompactionState:
    compaction_id: Incomplete
    state: Incomplete
    in_executing: Incomplete
    in_timeout: Incomplete
    completed: Incomplete
    def __init__(self, compaction_id: int, state: State, in_executing: int, in_timeout: int, completed: int) -> None: ...
    @property
    def state_name(self): ...

class Plan:
    sources: Incomplete
    target: Incomplete
    def __init__(self, sources: list, target: int) -> None: ...

class CompactionPlans:
    compaction_id: Incomplete
    state: Incomplete
    plans: Incomplete
    def __init__(self, compaction_id: int, state: int) -> None: ...

def cmp_consistency_level(l1: str | int, l2: str | int): ...
def get_consistency_level(consistency_level: str | int): ...

class Shard:
    def __init__(self, channel_name: str, shard_nodes: list, shard_leader: int) -> None: ...
    @property
    def channel_name(self) -> str: ...
    @property
    def shard_nodes(self): ...
    @property
    def shard_leader(self) -> int: ...

class Group:
    def __init__(self, group_id: int, shards: list[str], group_nodes: list[tuple], resource_group: str, num_outbound_node: dict) -> None: ...
    @property
    def id(self): ...
    @property
    def group_nodes(self): ...
    @property
    def shards(self): ...
    @property
    def resource_group(self): ...
    @property
    def num_outbound_node(self): ...

class Replica:
    def __init__(self, groups: list) -> None: ...
    @property
    def groups(self): ...

class ReplicaInfo:
    def __init__(self, replica_id: int, shards: list[str], nodes: list[tuple], resource_group: str, num_outbound_node: dict) -> None: ...
    @property
    def id(self): ...
    @property
    def group_nodes(self): ...
    @property
    def shards(self): ...
    @property
    def resource_group(self): ...
    @property
    def num_outbound_node(self): ...

class BulkInsertState:
    ImportPending: int
    ImportFailed: int
    ImportStarted: int
    ImportPersisted: int
    ImportCompleted: int
    ImportFailedAndCleaned: int
    ImportUnknownState: int
    FAILED_REASON: str
    IMPORT_FILES: str
    IMPORT_COLLECTION: str
    IMPORT_PARTITION: str
    IMPORT_PROGRESS: str
    state_2_state: ClassVar[dict]
    state_2_name: ClassVar[dict]
    def __init__(self, task_id: int, state: State, row_count: int, id_ranges: list, infos: dict, create_ts: int) -> None: ...
    @property
    def task_id(self): ...
    @property
    def row_count(self): ...
    @property
    def state(self): ...
    @property
    def state_name(self) -> str: ...
    @property
    def id_ranges(self): ...
    @property
    def ids(self): ...
    @property
    def infos(self): ...
    @property
    def failed_reason(self): ...
    @property
    def files(self): ...
    @property
    def collection_name(self): ...
    @property
    def partition_name(self): ...
    @property
    def create_timestamp(self): ...
    @property
    def create_time_str(self): ...
    @property
    def progress(self): ...

class GrantItem:
    def __init__(self, entity: Any) -> None: ...
    @property
    def object(self): ...
    @property
    def object_name(self): ...
    @property
    def db_name(self): ...
    @property
    def role_name(self): ...
    @property
    def grantor_name(self): ...
    @property
    def privilege(self): ...
    def __iter__(self): ...

class GrantInfo:
    def __init__(self, entities: list[milvus_types.RoleEntity]) -> None: ...
    @property
    def groups(self): ...

class PrivilegeGroupItem:
    def __init__(self, privilege_group: str, privileges: list[milvus_types.PrivilegeEntity]) -> None: ...
    @property
    def privilege_group(self): ...
    @property
    def privileges(self): ...

class PrivilegeGroupInfo:
    def __init__(self, results: list[milvus_types.PrivilegeGroupInfo]) -> None: ...
    @property
    def groups(self): ...

class UserItem:
    def __init__(self, username: str, entities: list[milvus_types.RoleEntity]) -> None: ...
    @property
    def username(self): ...
    @property
    def roles(self): ...

class UserInfo:
    def __init__(self, results: list[milvus_types.UserResult]) -> None: ...
    @property
    def groups(self): ...

class RoleItem:
    def __init__(self, role_name: str, entities: list[milvus_types.UserEntity]) -> None: ...
    @property
    def role_name(self): ...
    @property
    def users(self): ...

class RoleInfo:
    def __init__(self, results: list[milvus_types.RoleResult]) -> None: ...
    @property
    def groups(self): ...

class ResourceGroupInfo:
    def __init__(self, resource_group: Any) -> None: ...
    @property
    def name(self): ...
    @property
    def capacity(self): ...
    @property
    def num_available_node(self): ...
    @property
    def num_loaded_replica(self): ...
    @property
    def num_outgoing_node(self): ...
    @property
    def num_incoming_node(self): ...
    @property
    def config(self): ...
    @property
    def nodes(self): ...

class NodeInfo:
    def __init__(self, info: Any) -> None: ...
    @property
    def node_id(self) -> int: ...
    @property
    def address(self) -> str: ...
    @property
    def hostname(self) -> str: ...

ResourceGroupConfig: Incomplete
ResourceGroupLimit: Incomplete
ResourceGroupTransfer: Incomplete

class HybridExtraList(list):
    extra: Incomplete
    def __init__(self, lazy_field_data: list[Any], *args, extra: dict | None = None, dynamic_fields: list | None = None, strict_float32: bool = False, **kwargs) -> None: ...
    def __getitem__(self, index: int | slice): ...
    def __iter__(self): ...
    def materialize(self): ...

class ExtraList(list):
    extra: Incomplete
    def __init__(self, *args, extra: dict | None = None, **kwargs) -> None: ...

def get_cost_from_status(status: common_pb2.Status | None = None): ...
def get_cost_extra(status: common_pb2.Status | None = None): ...

class DatabaseInfo:
    @property
    def name(self) -> str: ...
    @property
    def properties(self) -> dict: ...
    def __init__(self, info: Any) -> None: ...
    def to_dict(self) -> dict[str, Any]: ...

class AnalyzeToken:
    dict: Incomplete
    def __init__(self, token: milvus_types.AnalyzerToken, with_hash: bool = False, with_detail: bool = False) -> None: ...
    @property
    def token(self): ...
    @property
    def start_offset(self): ...
    @property
    def end_offset(self): ...
    @property
    def position(self): ...
    @property
    def position_length(self): ...
    @property
    def hash(self): ...
    def __getitem__(self, key: str): ...

class AnalyzeResult:
    tokens: Incomplete
    def __init__(self, info: milvus_types.AnalyzerResult, with_hash: bool = False, with_detail: bool = False) -> None: ...
