import datetime
from .constants import LOGICAL_BITS as LOGICAL_BITS, LOGICAL_BITS_MASK as LOGICAL_BITS_MASK
from .types import DataType as DataType
from _typeshed import Incomplete
from datetime import timedelta
from pymilvus.exceptions import MilvusException as MilvusException, ParamError as ParamError
from pymilvus.grpc_gen.common_pb2 import Status as Status
from scipy.sparse import bsr_array as bsr_array, coo_array as coo_array, csc_array as csc_array, csr_array as csr_array, dia_array as dia_array, dok_array as dok_array, lil_array as lil_array, spmatrix as spmatrix
from typing import Any

MILVUS: str
ZILLIZ: str
valid_index_types: Incomplete
valid_index_params_keys: Incomplete
valid_binary_index_types: Incomplete
valid_binary_metric_types: Incomplete

def check_status(status: Status): ...
def is_successful(status: Status): ...
def hybridts_to_unixtime(ts: int): ...
def mkts_from_hybridts(hybridts: int, milliseconds: float = 0.0, delta: timedelta | None = None) -> int: ...
def mkts_from_unixtime(epoch: float, milliseconds: float = 0.0, delta: timedelta | None = None) -> int: ...
def mkts_from_datetime(d_time: datetime.datetime, milliseconds: float = 0.0, delta: timedelta | None = None) -> int: ...
def check_invalid_binary_vector(entities: list) -> bool: ...
def len_of(field_data: Any) -> int: ...
def traverse_rows_info(fields_info: Any, entities: list): ...
def traverse_info(fields_info: Any): ...
def traverse_upsert_info(fields_info: Any): ...
def get_params(search_params: dict): ...
def get_server_type(host: str): ...
def dumps(v: dict | str) -> str: ...

class SciPyHelper:
    @classmethod
    def is_spmatrix(cls, data: Any): ...
    @classmethod
    def is_sparray(cls, data: Any): ...
    @classmethod
    def is_scipy_sparse(cls, data: Any): ...
SparseRowOutputType = dict[int, float]
SparseMatrixInputType: Incomplete

def is_sparse_vector_type(data_type: DataType) -> bool: ...

dense_float_vector_type_set: Incomplete
dense_vector_type_set: Incomplete

def is_dense_float_vector_type(data_type: DataType) -> bool: ...
def is_float_vector_type(data_type: DataType): ...
def is_binary_vector_type(data_type: DataType): ...
def is_int_vector_type(data_type: DataType): ...
def is_vector_type(data_type: DataType): ...
def sparse_parse_single_row(data: bytes) -> SparseRowOutputType: ...
