[project]
name = "mcp-server-milvus"
version = "0.1.1.dev9"
description = "MCP server for Milvus"
authors = [
    { name = "D. Danchev", email = "12420863+danchev@users.noreply.github.com" },
]
classifiers = [
    "License :: OSI Approved :: Apache Software License",
    "Development Status :: 3 - Alpha",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Intended Audience :: Financial and Insurance Industry",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: Scientific/Engineering :: Interface Engine/Protocol Translator",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Typing :: Typed",
]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp[cli]>=1.25.0",
    "pymilvus>=2.6.3",
]

[project.urls]
Homepage = "https://github.com/danchev/mcp-server-milvus"
Issues = "https://github.com/danchev/mcp-server-milvus/issues"

[project.scripts]
mcp-server-milvus = "mcp_server_milvus.server:main"

[build-system]
requires = ["uv_build>=0.9.6,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.14.10",
    "ty>=0.0.8",
    {include-group = "commit"},
    {include-group = "test"},
]
test = [
    "pytest>=9.0.1",
    "pytest-cov>=7.0.0",
    "pytest-xdist>=3.8.0",
    "httpx>=0.28.1",
]
commit = [
    "commitizen>=4.11.0",
    "pre-commit>=4.5.1",
]

[tool.ruff]
line-length = 120
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "B", "Q"]
ignore = ["E203", "E501"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.1"
tag_format = "$version"
version_files = [
    "pyproject.toml:version"
]
update_changelog_on_bump = true

[tool.coverage.run]
command_line = "-m mcp_server_milvus"
branch = true
source = ["mcp_server_milvus"]
omit = [
    "tests/*",
    "src/mcp_server_milvus/__init__.py",
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise AssertionError",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "@abstractmethod",
]
