from _typeshed import Incomplete

GRPC_GENERATED_VERSION: str
GRPC_VERSION: Incomplete

class MilvusServiceStub:
    CreateCollection: Incomplete
    DropCollection: Incomplete
    HasCollection: Incomplete
    LoadCollection: Incomplete
    ReleaseCollection: Incomplete
    DescribeCollection: Incomplete
    BatchDescribeCollection: Incomplete
    GetCollectionStatistics: Incomplete
    ShowCollections: Incomplete
    AlterCollection: Incomplete
    AlterCollectionField: Incomplete
    CreatePartition: Incomplete
    DropPartition: Incomplete
    HasPartition: Incomplete
    LoadPartitions: Incomplete
    ReleasePartitions: Incomplete
    GetPartitionStatistics: Incomplete
    ShowPartitions: Incomplete
    GetLoadingProgress: Incomplete
    GetLoadState: Incomplete
    CreateAlias: Incomplete
    DropAlias: Incomplete
    AlterAlias: Incomplete
    DescribeAlias: Incomplete
    ListAliases: Incomplete
    CreateIndex: Incomplete
    AlterIndex: Incomplete
    DescribeIndex: Incomplete
    GetIndexStatistics: Incomplete
    GetIndexState: Incomplete
    GetIndexBuildProgress: Incomplete
    DropIndex: Incomplete
    Insert: Incomplete
    Delete: Incomplete
    Upsert: Incomplete
    Search: Incomplete
    HybridSearch: Incomplete
    Flush: Incomplete
    Query: Incomplete
    CalcDistance: Incomplete
    FlushAll: Incomplete
    AddCollectionField: Incomplete
    GetFlushState: Incomplete
    GetFlushAllState: Incomplete
    GetPersistentSegmentInfo: Incomplete
    GetQuerySegmentInfo: Incomplete
    GetReplicas: Incomplete
    Dummy: Incomplete
    RegisterLink: Incomplete
    GetMetrics: Incomplete
    GetComponentStates: Incomplete
    LoadBalance: Incomplete
    GetCompactionState: Incomplete
    ManualCompaction: Incomplete
    GetCompactionStateWithPlans: Incomplete
    Import: Incomplete
    GetImportState: Incomplete
    ListImportTasks: Incomplete
    CreateCredential: Incomplete
    UpdateCredential: Incomplete
    DeleteCredential: Incomplete
    ListCredUsers: Incomplete
    CreateRole: Incomplete
    DropRole: Incomplete
    OperateUserRole: Incomplete
    SelectRole: Incomplete
    SelectUser: Incomplete
    OperatePrivilege: Incomplete
    OperatePrivilegeV2: Incomplete
    SelectGrant: Incomplete
    GetVersion: Incomplete
    CheckHealth: Incomplete
    CreateResourceGroup: Incomplete
    DropResourceGroup: Incomplete
    UpdateResourceGroups: Incomplete
    TransferNode: Incomplete
    TransferReplica: Incomplete
    ListResourceGroups: Incomplete
    DescribeResourceGroup: Incomplete
    RenameCollection: Incomplete
    ListIndexedSegment: Incomplete
    DescribeSegmentIndexData: Incomplete
    Connect: Incomplete
    AllocTimestamp: Incomplete
    CreateDatabase: Incomplete
    DropDatabase: Incomplete
    ListDatabases: Incomplete
    AlterDatabase: Incomplete
    DescribeDatabase: Incomplete
    ReplicateMessage: Incomplete
    BackupRBAC: Incomplete
    RestoreRBAC: Incomplete
    CreatePrivilegeGroup: Incomplete
    DropPrivilegeGroup: Incomplete
    ListPrivilegeGroups: Incomplete
    OperatePrivilegeGroup: Incomplete
    RunAnalyzer: Incomplete
    AddFileResource: Incomplete
    RemoveFileResource: Incomplete
    ListFileResources: Incomplete
    AddUserTags: Incomplete
    DeleteUserTags: Incomplete
    GetUserTags: Incomplete
    ListUsersWithTag: Incomplete
    CreateRowPolicy: Incomplete
    DropRowPolicy: Incomplete
    ListRowPolicies: Incomplete
    def __init__(self, channel) -> None: ...

class MilvusServiceServicer:
    def CreateCollection(self, request, context) -> None: ...
    def DropCollection(self, request, context) -> None: ...
    def HasCollection(self, request, context) -> None: ...
    def LoadCollection(self, request, context) -> None: ...
    def ReleaseCollection(self, request, context) -> None: ...
    def DescribeCollection(self, request, context) -> None: ...
    def BatchDescribeCollection(self, request, context) -> None: ...
    def GetCollectionStatistics(self, request, context) -> None: ...
    def ShowCollections(self, request, context) -> None: ...
    def AlterCollection(self, request, context) -> None: ...
    def AlterCollectionField(self, request, context) -> None: ...
    def CreatePartition(self, request, context) -> None: ...
    def DropPartition(self, request, context) -> None: ...
    def HasPartition(self, request, context) -> None: ...
    def LoadPartitions(self, request, context) -> None: ...
    def ReleasePartitions(self, request, context) -> None: ...
    def GetPartitionStatistics(self, request, context) -> None: ...
    def ShowPartitions(self, request, context) -> None: ...
    def GetLoadingProgress(self, request, context) -> None: ...
    def GetLoadState(self, request, context) -> None: ...
    def CreateAlias(self, request, context) -> None: ...
    def DropAlias(self, request, context) -> None: ...
    def AlterAlias(self, request, context) -> None: ...
    def DescribeAlias(self, request, context) -> None: ...
    def ListAliases(self, request, context) -> None: ...
    def CreateIndex(self, request, context) -> None: ...
    def AlterIndex(self, request, context) -> None: ...
    def DescribeIndex(self, request, context) -> None: ...
    def GetIndexStatistics(self, request, context) -> None: ...
    def GetIndexState(self, request, context) -> None: ...
    def GetIndexBuildProgress(self, request, context) -> None: ...
    def DropIndex(self, request, context) -> None: ...
    def Insert(self, request, context) -> None: ...
    def Delete(self, request, context) -> None: ...
    def Upsert(self, request, context) -> None: ...
    def Search(self, request, context) -> None: ...
    def HybridSearch(self, request, context) -> None: ...
    def Flush(self, request, context) -> None: ...
    def Query(self, request, context) -> None: ...
    def CalcDistance(self, request, context) -> None: ...
    def FlushAll(self, request, context) -> None: ...
    def AddCollectionField(self, request, context) -> None: ...
    def GetFlushState(self, request, context) -> None: ...
    def GetFlushAllState(self, request, context) -> None: ...
    def GetPersistentSegmentInfo(self, request, context) -> None: ...
    def GetQuerySegmentInfo(self, request, context) -> None: ...
    def GetReplicas(self, request, context) -> None: ...
    def Dummy(self, request, context) -> None: ...
    def RegisterLink(self, request, context) -> None: ...
    def GetMetrics(self, request, context) -> None: ...
    def GetComponentStates(self, request, context) -> None: ...
    def LoadBalance(self, request, context) -> None: ...
    def GetCompactionState(self, request, context) -> None: ...
    def ManualCompaction(self, request, context) -> None: ...
    def GetCompactionStateWithPlans(self, request, context) -> None: ...
    def Import(self, request, context) -> None: ...
    def GetImportState(self, request, context) -> None: ...
    def ListImportTasks(self, request, context) -> None: ...
    def CreateCredential(self, request, context) -> None: ...
    def UpdateCredential(self, request, context) -> None: ...
    def DeleteCredential(self, request, context) -> None: ...
    def ListCredUsers(self, request, context) -> None: ...
    def CreateRole(self, request, context) -> None: ...
    def DropRole(self, request, context) -> None: ...
    def OperateUserRole(self, request, context) -> None: ...
    def SelectRole(self, request, context) -> None: ...
    def SelectUser(self, request, context) -> None: ...
    def OperatePrivilege(self, request, context) -> None: ...
    def OperatePrivilegeV2(self, request, context) -> None: ...
    def SelectGrant(self, request, context) -> None: ...
    def GetVersion(self, request, context) -> None: ...
    def CheckHealth(self, request, context) -> None: ...
    def CreateResourceGroup(self, request, context) -> None: ...
    def DropResourceGroup(self, request, context) -> None: ...
    def UpdateResourceGroups(self, request, context) -> None: ...
    def TransferNode(self, request, context) -> None: ...
    def TransferReplica(self, request, context) -> None: ...
    def ListResourceGroups(self, request, context) -> None: ...
    def DescribeResourceGroup(self, request, context) -> None: ...
    def RenameCollection(self, request, context) -> None: ...
    def ListIndexedSegment(self, request, context) -> None: ...
    def DescribeSegmentIndexData(self, request, context) -> None: ...
    def Connect(self, request, context) -> None: ...
    def AllocTimestamp(self, request, context) -> None: ...
    def CreateDatabase(self, request, context) -> None: ...
    def DropDatabase(self, request, context) -> None: ...
    def ListDatabases(self, request, context) -> None: ...
    def AlterDatabase(self, request, context) -> None: ...
    def DescribeDatabase(self, request, context) -> None: ...
    def ReplicateMessage(self, request, context) -> None: ...
    def BackupRBAC(self, request, context) -> None: ...
    def RestoreRBAC(self, request, context) -> None: ...
    def CreatePrivilegeGroup(self, request, context) -> None: ...
    def DropPrivilegeGroup(self, request, context) -> None: ...
    def ListPrivilegeGroups(self, request, context) -> None: ...
    def OperatePrivilegeGroup(self, request, context) -> None: ...
    def RunAnalyzer(self, request, context) -> None: ...
    def AddFileResource(self, request, context) -> None: ...
    def RemoveFileResource(self, request, context) -> None: ...
    def ListFileResources(self, request, context) -> None: ...
    def AddUserTags(self, request, context) -> None: ...
    def DeleteUserTags(self, request, context) -> None: ...
    def GetUserTags(self, request, context) -> None: ...
    def ListUsersWithTag(self, request, context) -> None: ...
    def CreateRowPolicy(self, request, context) -> None: ...
    def DropRowPolicy(self, request, context) -> None: ...
    def ListRowPolicies(self, request, context) -> None: ...

def add_MilvusServiceServicer_to_server(servicer, server) -> None: ...

class MilvusService:
    @staticmethod
    def CreateCollection(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DropCollection(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def HasCollection(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def LoadCollection(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ReleaseCollection(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DescribeCollection(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def BatchDescribeCollection(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetCollectionStatistics(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ShowCollections(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def AlterCollection(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def AlterCollectionField(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CreatePartition(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DropPartition(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def HasPartition(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def LoadPartitions(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ReleasePartitions(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetPartitionStatistics(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ShowPartitions(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetLoadingProgress(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetLoadState(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CreateAlias(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DropAlias(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def AlterAlias(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DescribeAlias(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListAliases(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CreateIndex(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def AlterIndex(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DescribeIndex(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetIndexStatistics(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetIndexState(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetIndexBuildProgress(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DropIndex(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def Insert(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def Delete(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def Upsert(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def Search(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def HybridSearch(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def Flush(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def Query(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CalcDistance(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def FlushAll(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def AddCollectionField(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetFlushState(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetFlushAllState(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetPersistentSegmentInfo(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetQuerySegmentInfo(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetReplicas(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def Dummy(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def RegisterLink(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetMetrics(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetComponentStates(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def LoadBalance(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetCompactionState(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ManualCompaction(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetCompactionStateWithPlans(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def Import(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetImportState(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListImportTasks(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CreateCredential(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def UpdateCredential(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DeleteCredential(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListCredUsers(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CreateRole(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DropRole(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def OperateUserRole(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def SelectRole(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def SelectUser(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def OperatePrivilege(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def OperatePrivilegeV2(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def SelectGrant(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetVersion(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CheckHealth(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CreateResourceGroup(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DropResourceGroup(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def UpdateResourceGroups(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def TransferNode(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def TransferReplica(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListResourceGroups(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DescribeResourceGroup(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def RenameCollection(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListIndexedSegment(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DescribeSegmentIndexData(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def Connect(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def AllocTimestamp(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CreateDatabase(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DropDatabase(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListDatabases(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def AlterDatabase(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DescribeDatabase(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ReplicateMessage(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def BackupRBAC(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def RestoreRBAC(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CreatePrivilegeGroup(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DropPrivilegeGroup(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListPrivilegeGroups(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def OperatePrivilegeGroup(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def RunAnalyzer(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def AddFileResource(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def RemoveFileResource(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListFileResources(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def AddUserTags(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DeleteUserTags(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def GetUserTags(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListUsersWithTag(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def CreateRowPolicy(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def DropRowPolicy(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
    @staticmethod
    def ListRowPolicies(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...

class ProxyServiceStub:
    RegisterLink: Incomplete
    def __init__(self, channel) -> None: ...

class ProxyServiceServicer:
    def RegisterLink(self, request, context) -> None: ...

def add_ProxyServiceServicer_to_server(servicer, server) -> None: ...

class ProxyService:
    @staticmethod
    def RegisterLink(request, target, options=(), channel_credentials=None, call_credentials=None, insecure: bool = False, compression=None, wait_for_ready=None, timeout=None, metadata=None): ...
