from _typeshed import Incomplete
from pymilvus.client.async_grpc_handler import AsyncGrpcHandler as AsyncGrpcHandler
from pymilvus.client.check import is_legal_address as is_legal_address, is_legal_host as is_legal_host, is_legal_port as is_legal_port
from pymilvus.client.grpc_handler import GrpcHandler as GrpcHandler
from pymilvus.exceptions import ConnectionConfigException as ConnectionConfigException, ConnectionNotExistException as ConnectionNotExistException, ExceptionsMessage as ExceptionsMessage
from pymilvus.settings import Config as Config
from typing import Callable

logger: Incomplete
VIRTUAL_PORT: int

def synchronized(func: Callable): ...

class SingleInstanceMetaClass(type):
    instance: Incomplete
    def __init__(cls, *args, **kwargs) -> None: ...
    def __call__(cls, *args, **kwargs): ...
    @synchronized
    def __new__(cls, *args, **kwargs): ...

class ReconnectHandler:
    connection_name: Incomplete
    conns: Incomplete
    is_idle_state: bool
    reconnect_lock: Incomplete
    def __init__(self, conns: object, connection_name: str, kwargs: object) -> None: ...
    def check_state_and_reconnect_later(self) -> None: ...
    def reconnect_on_idle(self, state: object): ...

class Connections(metaclass=SingleInstanceMetaClass):
    def __init__(self) -> None: ...
    def add_connection(self, **kwargs) -> None: ...
    def disconnect(self, alias: str): ...
    async def async_disconnect(self, alias: str): ...
    async def async_remove_connection(self, alias: str): ...
    def remove_connection(self, alias: str): ...
    def connect(self, alias: str = ..., user: str = '', password: str = '', db_name: str = 'default', token: str = '', _async: bool = False, **kwargs) -> None: ...
    def list_connections(self) -> list: ...
    def get_connection_addr(self, alias: str): ...
    def has_connection(self, alias: str) -> bool: ...

connections: Incomplete
