from .connections import connections as connections

def using_database(db_name: str, using: str = 'default'): ...
def create_database(db_name: str, using: str = 'default', timeout: float | None = None, **kwargs): ...
def drop_database(db_name: str, using: str = 'default', timeout: float | None = None): ...
def list_database(using: str = 'default', timeout: float | None = None) -> list: ...
def set_properties(db_name: str, properties: dict, using: str = 'default', timeout: float | None = None): ...
def describe_database(db_name: str, using: str = 'default', timeout: float | None = None): ...
