from .mutation import MutationResult as MutationResult
from pymilvus.client.search_result import SearchResult as SearchResult
from pymilvus.grpc_gen import schema_pb2 as schema_pb2
from typing import Any

class BaseFuture:
    def __init__(self, future: Any) -> None: ...
    def result(self) -> Any: ...
    def on_response(self, res: Any): ...
    def cancel(self): ...
    def done(self): ...

class _EmptySearchFuture:
    def result(self) -> SearchResult: ...
    def cancel(self) -> None: ...
    def done(self) -> None: ...

class MutationFuture(BaseFuture):
    def on_response(self, res: Any): ...

class SearchFuture(BaseFuture): ...
