from pymilvus.exceptions import CollectionNotExistException as CollectionNotExistException, ExceptionsMessage as ExceptionsMessage
from pymilvus.settings import Config as Config
from typing import TypeVar

Index = TypeVar('Index')
Collection = TypeVar('Collection')

class Index:
    def __init__(self, collection: Collection, field_name: str, index_params: dict, **kwargs) -> None: ...
    @property
    def params(self) -> dict: ...
    @property
    def collection_name(self) -> str: ...
    @property
    def field_name(self) -> str: ...
    @property
    def index_name(self) -> str: ...
    def __eq__(self, other: Index) -> bool: ...
    def to_dict(self): ...
    def drop(self, timeout: float | None = None, **kwargs): ...
