from typing import Any

class MutationResult:
    def __init__(self, mr: Any) -> None: ...
    @property
    def primary_keys(self): ...
    @property
    def insert_count(self): ...
    @property
    def delete_count(self): ...
    @property
    def upsert_count(self): ...
    @property
    def timestamp(self): ...
    @property
    def succ_count(self): ...
    @property
    def err_count(self): ...
    @property
    def succ_index(self): ...
    @property
    def err_index(self): ...
    @property
    def cost(self): ...
