import pandas as pd
from .mutation import MutationResult as MutationResult
from pymilvus.client import utils as utils
from pymilvus.client.abstract import BaseRanker as BaseRanker
from pymilvus.client.search_result import SearchResult as SearchResult
from pymilvus.client.types import Replica as Replica
from pymilvus.exceptions import MilvusException as MilvusException
from typing import TypeVar

Collection = TypeVar('Collection')
Partition = TypeVar('Partition')

class Partition:
    def __init__(self, collection: Collection | str, name: str, description: str = '', **kwargs) -> None: ...
    @property
    def description(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def is_empty(self) -> bool: ...
    @property
    def num_entities(self) -> int: ...
    def flush(self, timeout: float | None = None, **kwargs): ...
    def drop(self, timeout: float | None = None, **kwargs): ...
    def load(self, replica_number: int | None = None, timeout: float | None = None, **kwargs): ...
    def release(self, timeout: float | None = None, **kwargs): ...
    def insert(self, data: list | pd.DataFrame | utils.SparseMatrixInputType, timeout: float | None = None, **kwargs) -> MutationResult: ...
    def delete(self, expr: str, timeout: float | None = None, **kwargs): ...
    def upsert(self, data: list | pd.DataFrame | utils.SparseMatrixInputType, timeout: float | None = None, **kwargs) -> MutationResult: ...
    def search(self, data: list | utils.SparseMatrixInputType, anns_field: str, param: dict, limit: int, expr: str | None = None, output_fields: list[str] | None = None, timeout: float | None = None, round_decimal: int = -1, **kwargs) -> SearchResult: ...
    def hybrid_search(self, reqs: list, rerank: BaseRanker, limit: int, output_fields: list[str] | None = None, timeout: float | None = None, round_decimal: int = -1, **kwargs): ...
    def query(self, expr: str, output_fields: list[str] | None = None, timeout: float | None = None, **kwargs): ...
    def get_replicas(self, timeout: float | None = None, **kwargs) -> Replica: ...
