from .connections import connections as connections
from _typeshed import Incomplete

INCLUDE_USER_INFO: Incomplete
NOT_INCLUDE_USER_INFO: Incomplete

class Role:
    def __init__(self, name: str, using: str = 'default', **kwargs) -> None: ...
    @property
    def name(self): ...
    def create(self): ...
    def drop(self): ...
    def add_user(self, username: str): ...
    def remove_user(self, username: str): ...
    def get_users(self): ...
    def is_exist(self): ...
    def grant(self, object: str, object_name: str, privilege: str, db_name: str = ''): ...
    def revoke(self, object: str, object_name: str, privilege: str, db_name: str = ''): ...
    def grant_v2(self, privilege: str, collection_name: str, db_name: str | None = None): ...
    def revoke_v2(self, privilege: str, collection_name: str, db_name: str | None = None): ...
    def list_grant(self, object: str, object_name: str, db_name: str = ''): ...
    def list_grants(self, db_name: str = ''): ...
    def create_privilege_group(self, privilege_group: str): ...
    def drop_privilege_group(self, privilege_group: str): ...
    def list_privilege_groups(self): ...
    def add_privileges_to_group(self, privilege_group: str, privileges: list): ...
    def remove_privileges_from_group(self, privilege_group: str, privileges: list): ...
