import pandas as pd
from .constants import COMMON_TYPE_PARAMS as COMMON_TYPE_PARAMS
from .types import DataType as DataType, infer_dtype_by_scalar_data as infer_dtype_by_scalar_data, infer_dtype_bydata as infer_dtype_bydata, map_numpy_dtype_to_datatype as map_numpy_dtype_to_datatype
from _typeshed import Incomplete
from pymilvus.client.types import FunctionType as FunctionType
from pymilvus.exceptions import AutoIDException as AutoIDException, CannotInferSchemaException as CannotInferSchemaException, ClusteringKeyException as ClusteringKeyException, DataNotMatchException as DataNotMatchException, DataTypeNotSupportException as DataTypeNotSupportException, ExceptionsMessage as ExceptionsMessage, FieldTypeException as FieldTypeException, FieldsTypeException as FieldsTypeException, FunctionsTypeException as FunctionsTypeException, ParamError as ParamError, PartitionKeyException as PartitionKeyException, PrimaryKeyException as PrimaryKeyException, SchemaNotReadyException as SchemaNotReadyException
from typing import Any

def validate_primary_key(primary_field: Any): ...
def validate_partition_key(partition_key_field_name: Any, partition_key_field: Any, primary_field_name: Any): ...
def validate_clustering_key(clustering_key_field_name: Any, clustering_key_field: Any): ...

class CollectionSchema:
    def __init__(self, fields: list, description: str = '', functions: list | None = None, **kwargs) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other: object): ...
    @classmethod
    def construct_from_dict(cls, raw: dict): ...
    @property
    def primary_field(self): ...
    @property
    def partition_key_field(self): ...
    @property
    def fields(self): ...
    @property
    def functions(self): ...
    @property
    def description(self): ...
    @property
    def auto_id(self): ...
    @auto_id.setter
    def auto_id(self, value: bool): ...
    @property
    def enable_dynamic_field(self): ...
    @enable_dynamic_field.setter
    def enable_dynamic_field(self, value: bool): ...
    def to_dict(self): ...
    def verify(self) -> None: ...
    def add_field(self, field_name: str, datatype: DataType, **kwargs): ...
    def add_function(self, function: Function): ...

class FieldSchema:
    name: Incomplete
    is_primary: Incomplete
    is_dynamic: Incomplete
    nullable: Incomplete
    auto_id: Incomplete
    is_partition_key: Incomplete
    is_clustering_key: Incomplete
    default_value: Incomplete
    element_type: Incomplete
    is_function_output: bool
    def __init__(self, name: str, dtype: DataType, description: str = '', **kwargs) -> None: ...
    def __deepcopy__(self, memodict: dict | None = None): ...
    @classmethod
    def construct_from_dict(cls, raw: dict): ...
    def to_dict(self): ...
    def __getattr__(self, item: str): ...
    def __eq__(self, other: object): ...
    @property
    def description(self): ...
    @property
    def params(self): ...
    @property
    def dtype(self) -> DataType: ...

class Function:
    def __init__(self, name: str, function_type: FunctionType, input_field_names: str | list[str], output_field_names: str | list[str] | None = None, description: str = '', params: dict | None = None) -> None: ...
    @property
    def name(self): ...
    @property
    def description(self): ...
    @property
    def type(self): ...
    @property
    def input_field_names(self): ...
    @property
    def output_field_names(self): ...
    @property
    def params(self): ...
    def verify(self, schema: CollectionSchema): ...
    @classmethod
    def construct_from_dict(cls, raw: dict): ...
    def to_dict(self): ...
    def __eq__(self, value: object) -> bool: ...

def is_valid_insert_data(data: pd.DataFrame | list | dict) -> bool: ...
def is_row_based(data: dict | list[dict]) -> bool: ...
def check_is_row_based(data: list[list] | list[dict] | dict | pd.DataFrame) -> bool: ...
def check_insert_schema(schema: CollectionSchema, data: list[list] | pd.DataFrame): ...
def check_upsert_schema(schema: CollectionSchema, data: list[list] | pd.DataFrame): ...
def construct_fields_from_dataframe(df: pd.DataFrame) -> list[FieldSchema]: ...
def prepare_fields_from_dataframe(df: pd.DataFrame): ...
def check_schema(schema: CollectionSchema): ...
def infer_default_value_bydata(data: Any): ...
