from .connections import connections as connections
from datetime import datetime, timedelta, timezone
from pymilvus.client.types import BulkInsertState as BulkInsertState, ResourceGroupConfig as ResourceGroupConfig
from pymilvus.exceptions import MilvusException as MilvusException
from typing import Mapping

def mkts_from_hybridts(hybridts: int, milliseconds: float = 0.0, delta: timedelta | None = None): ...
def mkts_from_unixtime(epoch: float, milliseconds: float = 0.0, delta: timedelta | None = None): ...
def mkts_from_datetime(d_time: datetime, milliseconds: float = 0.0, delta: timedelta | None = None): ...
def hybridts_to_datetime(hybridts: int, tz: timezone | None = None): ...
def hybridts_to_unixtime(hybridts: int): ...
def loading_progress(collection_name: str, partition_names: list[str] | None = None, using: str = 'default', timeout: float | None = None): ...
def load_state(collection_name: str, partition_names: list[str] | None = None, using: str = 'default', timeout: float | None = None): ...
def wait_for_loading_complete(collection_name: str, partition_names: list[str] | None = None, timeout: float | None = None, using: str = 'default'): ...
def index_building_progress(collection_name: str, index_name: str = '', using: str = 'default', timeout: float | None = None): ...
def wait_for_index_building_complete(collection_name: str, index_name: str = '', timeout: float | None = None, using: str = 'default'): ...
def has_collection(collection_name: str, using: str = 'default', timeout: float | None = None): ...
def has_partition(collection_name: str, partition_name: str, using: str = 'default', timeout: float | None = None) -> bool: ...
def drop_collection(collection_name: str, timeout: float | None = None, using: str = 'default'): ...
def rename_collection(old_collection_name: str, new_collection_name: str, new_db_name: str = '', timeout: float | None = None, using: str = 'default'): ...
def list_collections(timeout: float | None = None, using: str = 'default') -> list: ...
def load_balance(collection_name: str, src_node_id: int, dst_node_ids: list[int] | None = None, sealed_segment_ids: list[int] | None = None, timeout: float | None = None, using: str = 'default'): ...
def get_query_segment_info(collection_name: str, timeout: float | None = None, using: str = 'default'): ...
def create_alias(collection_name: str, alias: str, timeout: float | None = None, using: str = 'default'): ...
def drop_alias(alias: str, timeout: float | None = None, using: str = 'default'): ...
def alter_alias(collection_name: str, alias: str, timeout: float | None = None, using: str = 'default'): ...
def list_aliases(collection_name: str, timeout: float | None = None, using: str = 'default'): ...
def do_bulk_insert(collection_name: str, files: list[str], partition_name: str | None = None, timeout: float | None = None, using: str = 'default', **kwargs) -> int: ...
def get_bulk_insert_state(task_id: int, timeout: float | None = None, using: str = 'default', **kwargs) -> BulkInsertState: ...
def list_bulk_insert_tasks(limit: int = 0, collection_name: str | None = None, timeout: float | None = None, using: str = 'default', **kwargs) -> list: ...
def reset_password(user: str, old_password: str, new_password: str, using: str = 'default', timeout: float | None = None): ...
def create_user(user: str, password: str, using: str = 'default', timeout: float | None = None): ...
def update_password(user: str, old_password: str, new_password: str, using: str = 'default', timeout: float | None = None): ...
def delete_user(user: str, using: str = 'default', timeout: float | None = None): ...
def list_usernames(using: str = 'default', timeout: float | None = None): ...
def list_roles(include_user_info: bool, using: str = 'default', timeout: float | None = None): ...
def list_user(username: str, include_role_info: bool, using: str = 'default', timeout: float | None = None): ...
def list_users(include_role_info: bool, using: str = 'default', timeout: float | None = None): ...
def get_server_version(using: str = 'default', timeout: float | None = None) -> str: ...
def create_resource_group(name: str, using: str = 'default', timeout: float | None = None, **kwargs): ...
def update_resource_groups(configs: Mapping[str, ResourceGroupConfig], using: str = 'default', timeout: float | None = None): ...
def drop_resource_group(name: str, using: str = 'default', timeout: float | None = None): ...
def describe_resource_group(name: str, using: str = 'default', timeout: float | None = None): ...
def list_resource_groups(using: str = 'default', timeout: float | None = None): ...
def transfer_node(source_group: str, target_group: str, num_nodes: int, using: str = 'default', timeout: float | None = None): ...
def transfer_replica(source_group: str, target_group: str, collection_name: str, num_replicas: int, using: str = 'default', timeout: float | None = None): ...
def flush_all(using: str = 'default', timeout: float | None = None, **kwargs): ...
def get_server_type(using: str = 'default'): ...
def list_indexes(collection_name: str, using: str = 'default', timeout: float | None = None, **kwargs): ...
