class IndexParam:
    def __init__(self, field_name: str, index_type: str, index_name: str, **kwargs) -> None: ...
    @property
    def field_name(self): ...
    @property
    def index_name(self): ...
    @property
    def index_type(self): ...
    def get_index_configs(self) -> dict: ...
    def to_dict(self) -> dict: ...
    def __eq__(self, other: None): ...

class IndexParams(list):
    def __init__(self, *args, **kwargs) -> None: ...
    def add_index(self, field_name: str, index_type: str = '', index_name: str = '', **kwargs): ...
