from ._utils import create_connection as create_connection
from .check import validate_param as validate_param
from .index import IndexParam as IndexParam, IndexParams as IndexParams
from _typeshed import Incomplete
from pymilvus.client.abstract import AnnSearchRequest as AnnSearchRequest, BaseRanker as BaseRanker
from pymilvus.client.constants import DEFAULT_CONSISTENCY_LEVEL as DEFAULT_CONSISTENCY_LEVEL
from pymilvus.client.search_iterator import SearchIteratorV2 as SearchIteratorV2
from pymilvus.client.types import ExceptionsMessage as ExceptionsMessage, LoadState as LoadState, OmitZeroDict as OmitZeroDict, ReplicaInfo as ReplicaInfo, ResourceGroupConfig as ResourceGroupConfig
from pymilvus.client.utils import get_params as get_params, is_vector_type as is_vector_type
from pymilvus.exceptions import DataTypeNotMatchException as DataTypeNotMatchException, ErrorCode as ErrorCode, MilvusException as MilvusException, ParamError as ParamError, PrimaryKeyException as PrimaryKeyException, ServerVersionIncompatibleException as ServerVersionIncompatibleException
from pymilvus.orm import utility as utility
from pymilvus.orm.collection import CollectionSchema as CollectionSchema, FieldSchema as FieldSchema, Function as Function
from pymilvus.orm.connections import connections as connections
from pymilvus.orm.constants import FIELDS as FIELDS, METRIC_TYPE as METRIC_TYPE, TYPE as TYPE, UNLIMITED as UNLIMITED
from pymilvus.orm.iterator import QueryIterator as QueryIterator, SearchIterator as SearchIterator
from pymilvus.orm.types import DataType as DataType

logger: Incomplete

class MilvusClient:
    is_self_hosted: Incomplete
    def __init__(self, uri: str = 'http://localhost:19530', user: str = '', password: str = '', db_name: str = '', token: str = '', timeout: float | None = None, **kwargs) -> None: ...
    def create_collection(self, collection_name: str, dimension: int | None = None, primary_field_name: str = 'id', id_type: str = 'int', vector_field_name: str = 'vector', metric_type: str = 'COSINE', auto_id: bool = False, timeout: float | None = None, schema: CollectionSchema | None = None, index_params: IndexParams | None = None, **kwargs): ...
    def create_index(self, collection_name: str, index_params: IndexParams, timeout: float | None = None, **kwargs): ...
    def insert(self, collection_name: str, data: dict | list[dict], timeout: float | None = None, partition_name: str | None = '', **kwargs) -> dict: ...
    def upsert(self, collection_name: str, data: dict | list[dict], timeout: float | None = None, partition_name: str | None = '', **kwargs) -> dict: ...
    def hybrid_search(self, collection_name: str, reqs: list[AnnSearchRequest], ranker: BaseRanker | Function, limit: int = 10, output_fields: list[str] | None = None, timeout: float | None = None, partition_names: list[str] | None = None, **kwargs) -> list[list[dict]]: ...
    def search(self, collection_name: str, data: list[list] | list, filter: str = '', limit: int = 10, output_fields: list[str] | None = None, search_params: dict | None = None, timeout: float | None = None, partition_names: list[str] | None = None, anns_field: str | None = None, ranker: Function | None = None, **kwargs) -> list[list[dict]]: ...
    def query(self, collection_name: str, filter: str = '', output_fields: list[str] | None = None, timeout: float | None = None, ids: list | str | int | None = None, partition_names: list[str] | None = None, **kwargs) -> list[dict]: ...
    def query_iterator(self, collection_name: str, batch_size: int | None = 1000, limit: int | None = ..., filter: str | None = '', output_fields: list[str] | None = None, partition_names: list[str] | None = None, timeout: float | None = None, **kwargs): ...
    def search_iterator(self, collection_name: str, data: list[list] | list, batch_size: int | None = 1000, filter: str | None = None, limit: int | None = ..., output_fields: list[str] | None = None, search_params: dict | None = None, timeout: float | None = None, partition_names: list[str] | None = None, anns_field: str | None = None, round_decimal: int = -1, **kwargs) -> SearchIteratorV2 | SearchIterator: ...
    def get(self, collection_name: str, ids: list | str | int, output_fields: list[str] | None = None, timeout: float | None = None, partition_names: list[str] | None = None, **kwargs) -> list[dict]: ...
    def delete(self, collection_name: str, ids: list | str | int | None = None, timeout: float | None = None, filter: str | None = None, partition_name: str | None = None, **kwargs) -> dict[str, int]: ...
    def get_collection_stats(self, collection_name: str, timeout: float | None = None) -> dict: ...
    def describe_collection(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    def has_collection(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    def list_collections(self, **kwargs): ...
    def drop_collection(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    def rename_collection(self, old_name: str, new_name: str, target_db: str | None = '', timeout: float | None = None, **kwargs): ...
    @classmethod
    def create_schema(cls, **kwargs): ...
    @classmethod
    def create_field_schema(cls, name: str, data_type: DataType, desc: str = '', **kwargs) -> FieldSchema: ...
    @classmethod
    def prepare_index_params(cls, field_name: str = '', **kwargs) -> IndexParams: ...
    def close(self) -> None: ...
    def load_collection(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    def release_collection(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    def get_load_state(self, collection_name: str, partition_name: str | None = '', timeout: float | None = None, **kwargs) -> dict: ...
    def refresh_load(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    def list_indexes(self, collection_name: str, field_name: str | None = '', **kwargs): ...
    def drop_index(self, collection_name: str, index_name: str, timeout: float | None = None, **kwargs): ...
    def describe_index(self, collection_name: str, index_name: str, timeout: float | None = None, **kwargs) -> dict: ...
    def alter_index_properties(self, collection_name: str, index_name: str, properties: dict, timeout: float | None = None, **kwargs): ...
    def drop_index_properties(self, collection_name: str, index_name: str, property_keys: list[str], timeout: float | None = None, **kwargs): ...
    def alter_collection_properties(self, collection_name: str, properties: dict, timeout: float | None = None, **kwargs): ...
    def drop_collection_properties(self, collection_name: str, property_keys: list[str], timeout: float | None = None, **kwargs): ...
    def alter_collection_field(self, collection_name: str, field_name: str, field_params: dict, timeout: float | None = None, **kwargs): ...
    def add_collection_field(self, collection_name: str, field_name: str, data_type: DataType, desc: str = '', timeout: float | None = None, **kwargs): ...
    def create_partition(self, collection_name: str, partition_name: str, timeout: float | None = None, **kwargs): ...
    def drop_partition(self, collection_name: str, partition_name: str, timeout: float | None = None, **kwargs): ...
    def has_partition(self, collection_name: str, partition_name: str, timeout: float | None = None, **kwargs) -> bool: ...
    def list_partitions(self, collection_name: str, timeout: float | None = None, **kwargs) -> list[str]: ...
    def load_partitions(self, collection_name: str, partition_names: str | list[str], timeout: float | None = None, **kwargs): ...
    def release_partitions(self, collection_name: str, partition_names: str | list[str], timeout: float | None = None, **kwargs): ...
    def get_partition_stats(self, collection_name: str, partition_name: str, timeout: float | None = None, **kwargs) -> dict: ...
    def create_user(self, user_name: str, password: str, timeout: float | None = None, **kwargs): ...
    def drop_user(self, user_name: str, timeout: float | None = None, **kwargs): ...
    def update_password(self, user_name: str, old_password: str, new_password: str, reset_connection: bool | None = False, timeout: float | None = None, **kwargs): ...
    def list_users(self, timeout: float | None = None, **kwargs): ...
    def describe_user(self, user_name: str, timeout: float | None = None, **kwargs): ...
    def grant_role(self, user_name: str, role_name: str, timeout: float | None = None, **kwargs): ...
    def revoke_role(self, user_name: str, role_name: str, timeout: float | None = None, **kwargs): ...
    def create_role(self, role_name: str, timeout: float | None = None, **kwargs): ...
    def drop_role(self, role_name: str, force_drop: bool = False, timeout: float | None = None, **kwargs): ...
    def describe_role(self, role_name: str, timeout: float | None = None, **kwargs) -> dict: ...
    def list_roles(self, timeout: float | None = None, **kwargs): ...
    def grant_privilege(self, role_name: str, object_type: str, privilege: str, object_name: str, db_name: str | None = '', timeout: float | None = None, **kwargs): ...
    def revoke_privilege(self, role_name: str, object_type: str, privilege: str, object_name: str, db_name: str | None = '', timeout: float | None = None, **kwargs): ...
    def grant_privilege_v2(self, role_name: str, privilege: str, collection_name: str, db_name: str | None = None, timeout: float | None = None, **kwargs): ...
    def revoke_privilege_v2(self, role_name: str, privilege: str, collection_name: str, db_name: str | None = None, timeout: float | None = None, **kwargs): ...
    def create_alias(self, collection_name: str, alias: str, timeout: float | None = None, **kwargs): ...
    def drop_alias(self, alias: str, timeout: float | None = None, **kwargs): ...
    def alter_alias(self, collection_name: str, alias: str, timeout: float | None = None, **kwargs): ...
    def describe_alias(self, alias: str, timeout: float | None = None, **kwargs) -> dict: ...
    def list_aliases(self, collection_name: str = '', timeout: float | None = None, **kwargs) -> list[str]: ...
    def using_database(self, db_name: str, **kwargs): ...
    def use_database(self, db_name: str, **kwargs): ...
    def create_database(self, db_name: str, properties: dict | None = None, timeout: float | None = None, **kwargs): ...
    def drop_database(self, db_name: str, **kwargs): ...
    def list_databases(self, timeout: float | None = None, **kwargs) -> list[str]: ...
    def describe_database(self, db_name: str, **kwargs) -> dict: ...
    def alter_database_properties(self, db_name: str, properties: dict, **kwargs): ...
    def drop_database_properties(self, db_name: str, property_keys: list[str], **kwargs): ...
    def flush(self, collection_name: str, timeout: float | None = None, **kwargs): ...
    def compact(self, collection_name: str, is_clustering: bool | None = False, timeout: float | None = None, **kwargs) -> int: ...
    def get_compaction_state(self, job_id: int, timeout: float | None = None, **kwargs) -> str: ...
    def get_server_version(self, timeout: float | None = None, **kwargs) -> str: ...
    def create_privilege_group(self, group_name: str, timeout: float | None = None, **kwargs): ...
    def drop_privilege_group(self, group_name: str, timeout: float | None = None, **kwargs): ...
    def list_privilege_groups(self, timeout: float | None = None, **kwargs) -> list[dict[str, str]]: ...
    def add_privileges_to_group(self, group_name: str, privileges: list[str], timeout: float | None = None, **kwargs): ...
    def remove_privileges_from_group(self, group_name: str, privileges: list[str], timeout: float | None = None, **kwargs): ...
    def create_resource_group(self, name: str, timeout: float | None = None, **kwargs): ...
    def update_resource_groups(self, configs: dict[str, ResourceGroupConfig], timeout: float | None = None): ...
    def drop_resource_group(self, name: str, timeout: float | None = None): ...
    def describe_resource_group(self, name: str, timeout: float | None = None): ...
    def list_resource_groups(self, timeout: float | None = None): ...
    def transfer_replica(self, source_group: str, target_group: str, collection_name: str, num_replicas: int, timeout: float | None = None): ...
    def describe_replica(self, collection_name: str, timeout: float | None = None, **kwargs) -> list[ReplicaInfo]: ...
    def run_analyzer(self, texts: str | list[str], analyzer_params: str | dict | None = None, with_hash: bool = False, with_detail: bool = False, collection_name: str | None = None, field_name: str | None = None, analyzer_names: str | list[str] | None = None, timeout: float | None = None): ...
